- hosts: all

  vars:
    nginx_package_name: "nginx"
    ds_port: 9378

    nginx_vhosts:
      - listen: "80 default_server"
        server_name: “”
        server_tokens: "off"
        template: "{{ nginx_vhost_template }}"
        filename: "onlyoffice.conf"
        extra_parameters: |
          location /ds_path/ {
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $proxy_connection;
              proxy_set_header X-Forwarded-Host $the_host/ds_path;
              proxy_set_header X-Forwarded-Proto $the_scheme;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 

              proxy_pass http://localhost:{{ ds_port }}/;
              proxy_http_version 1.1;
          }

    postgresql_global_config_options:
      - option: listen_addresses
        value: "*"
      - option: unix_socket_directories
        value: '{{ postgresql_unix_socket_directories | join(",") }}'
      - option: log_directory
        value: 'log'

    postgresql_hba_entries:
      - type: local
        database: all
        user: postgres
        auth_method: peer
      - type: local
        database: all
        user: all
        auth_method: peer 
      - type: host
        database: all
        user: all
        address: 127.0.0.1/32
        auth_method: md5
      - type: host
        database: all
        user: all
        address: ::1/128
        auth_method: md5
      - type: host
        database: all
        user: all
        address: 0.0.0.0/0
        auth_method: md5

    postgresql_databases:
      - name: "{{ db_server_name }}"

    postgresql_users:
      - name: "{{ db_server_user }}"
        password: "{{ db_server_pass }}"

    rabbitmq_users:
      - name: "{{ rabbitmq_server_user }}"
        password: "{{ rabbitmq_server_pass }}"
        vhost: "{{ rabbitmq_server_vpath }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator

    rabbitmq_users_remove: []

    redis_bind_interface: 0.0.0.0

  roles:
    - geerlingguy.postgresql
    - onlyoffice.rabbitmq
    - geerlingguy.redis
    - onlyoffice.documentserver
    - geerlingguy.nginx
