---
name: Test
'on':
  workflow_dispatch:
  push: 
    branches: 
      - 'feature/*'
      - 'bugfix/*'
      - 'master'

defaults:
  run:
    working-directory: 'document-server-proxy/tests/nginx'

jobs:

  proxy-smoke:
    name: Proxy smoke test (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nginx HTTPS to HTTP
            path: nginx/proxy-https-to-http
            url: https://localhost
            ssl: 'true'
            config: ../../../nginx/proxy-https-to-http.conf
            traefik_host: ''
            check_websocket_headers: 'true'
          - name: traefik HTTPS to HTTP
            path: traefik/proxy-https-to-http
            url: https://localhost
            ssl: 'true'
            config: ../../../traefik/v1/proxy-https-to-http.toml
            traefik_host: ''
            check_websocket_headers: 'true'
          - name: nginx virtual path
            path: nginx/proxy-to-virtual-path
            url: http://localhost/documentserver-virtual-path
            ssl: 'false'
            config: ''
            traefik_host: ''
            check_websocket_headers: 'false'

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'document-server-proxy'

      - name: Show Docker Compose version.
        run: docker compose version || docker-compose --version
        working-directory: 'document-server-proxy/tests'

      - name: Run proxy smoke test.
        run: ./test.sh
        working-directory: 'document-server-proxy/tests'
        env:
          path: ${{ matrix.path }}
          url: ${{ matrix.url }}
          ssl: ${{ matrix.ssl }}
          config: ${{ matrix.config }}
          traefik_host: ${{ matrix.traefik_host }}
          check_websocket_headers: ${{ matrix.check_websocket_headers }}

  molecule:
    name: Molecule test on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos8
          - debian9
          - debian10
          - debian11
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'document-server-proxy'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[lint,docker] docker yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_NO_LOG: 'false'
          MOLECULE_DISTRO: ${{ matrix.distro }}
